url:         http://sethrylan.org/bayesian
baseurl:     /
title:       An Educated Guess
port:        4000
safe:        false
lsi:         true
pygments:    true
permalink:   date
markdown:    maruku
maruku:
  use_tex:   false
  use_divs:  false
  png_dir:   images/latex
  png_url:   /images/latex
googleanalytics:
  account:   UA-33138107-1
author:
  name:      Seth Rylan Gainey
  email:     seth@sethrylan.org
  obfuscatedemail: mailto:seth{at}sethrylan{dot}org
navigation:
  - text:    Home
    url:     /index.html
